version: 0.2

phases:
    install:
        commands:
            - echo started...

    pre_build:
        commands:
            - echo building npm
            - npm install

    build:
        commands:
            - echo deployment started..
            - aws cloudformation package --template-file sam/app/template.yaml --s3-bucket greetme-cicd --output-template-file packaged-template.yaml

    post_build:
        commands:
            - echo deployment complete..
artifacts:
  files:
    - packaged-template.yaml
