AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'cicd

  Sample SAM Template for cicd

  '
Globals:
  Function:
    Timeout: 3
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://greetme-cicd/de969f5d8bcef4793c561e51bf36aa2a
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  Build:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
        - BuildRole
        - Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
        Version: '2012-10-17'
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
        Version: '2012-10-17'
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
        - PipelineRole
        - Arn
      Stages:
      - Actions:
        - ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: '1'
          Configuration:
            Owner: yagnaguru-hobsons
            Repo: cicd
            Branch: master
            OAuthToken: b7b04b4acaa78fffed134ac6d4ad77b17f4d5359
            PollForSourceChanges: false
          Name: GitHub_Source
          OutputArtifacts:
          - Name: website_source_code
          RunOrder: 1
        Name: Source
      - Actions:
        - ActionTypeId:
            Category: Build
            Owner: AWS
            Provider: CodeBuild
            Version: '1'
          Configuration:
            ProjectName:
              Ref: Build
          InputArtifacts:
          - Name: website_source_code
          Name: Build_website
          OutputArtifacts:
          - Name: BuildOutput
          RoleArn:
            Fn::GetAtt:
            - BuildCodePipelineActionRole
            - Arn
          RunOrder: 1
        Name: Build
      - Name: Deployment_Approval
        Actions:
        - Name: Approval
          ActionTypeId:
            Category: Approval
            Owner: AWS
            Provider: Manual
            Version: '1'
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: S3Deploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: S3
            Version: '1'
          InputArtifacts:
          - Name: BuildOutput
          Configuration:
            BucketName: greetme-cicd
            Extract: 'true'
          RunOrder: 1
      ArtifactStore:
        Location: greetme-cicd
        Type: S3
    DependsOn:
    - PipelineRole
  BuildCodePipelineActionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
            - '*'
        Version: '2012-10-17'
  GithubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: b7b04b4acaa78fffed134ac6d4ad77b17f4d5359
      RegisterWithThirdParty: 'true'
      Filters:
      - JsonPath: $.ref
        MatchEquals: refs/heads/master
      TargetPipeline:
        Ref: Pipeline
      TargetAction: GitHub_Source
      TargetPipelineVersion:
        Fn::GetAtt:
        - Pipeline
        - Version
